# Generated by Django 3.1.4 on 2020-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Proyecto')),
                ('short_description', models.CharField(max_length=500, verbose_name='Descripción corta')),
                ('full_description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagen')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('deprecated', 'Abandonado')], default='in_progress', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de incio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('tags', models.ManyToManyField(to='portfolio.Tag')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('-end_date', 'status'),
            },
        ),
    ]
